version: "3"

services:
  bilab_es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: bilab_es
    environment:
      - cluster.name=bilab-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - bilab_es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - bilab_es_network
  bilab_kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: bilab_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://bilab_es:9200
    depends_on:
      - bilab_es
    ports:
      - 5601:5601
    networks:
      - bilab_es_network

volumes:
  bilab_es_data:
    driver: local

networks:
  bilab_es_network:
    driver: bridge
